name: Purge cache of package repository

on:
  workflow_dispatch:

jobs:
  cloudflare:
    runs-on: ubuntu-20.04

    steps:
      - name: Purge cache of decompressor
        run: |
          curl https://decompressor.jesec.workers.dev/?decompress=https://nightly.link/jesec/rtorrent/workflows/publish-rolling/master/rtorrent-deb-amd64.zip&purge=true
          curl https://decompressor.jesec.workers.dev/?decompress=https://nightly.link/jesec/rtorrent/workflows/publish-rolling/master/rtorrent-deb-arm64.zip&purge=true

  vercel:
    needs: cloudflare
    runs-on: ubuntu-20.04

    steps:
      - name: Regenerate meta of packages
        run: |
          curl -X POST "https://api.vercel.com/v12/now/deployments?forceNew=1" -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" -H "Content-Type: application/json" -d '{"name":"deb","gitSource":{"ref":"master","type":"github","sha":"${{ github.sha }}","repoId":330383260},"target":"production"}'
